### ISSUE TITLE
code for scene editing?

### ISSUE THREAD

**Issue by YandanYang** [ianhuang0630/BlenderAlchemyOfficial#2]
Hi,
Will you release the code or prompt for scene layout editing? Does GPT work stable for scene editing?

**Comment by ianhuang0630** [comment]
Sure! 2 steps you should follow:

Step 1) download the `livingroom_scene.blend` file from https://drive.google.com/drive/folders/1TNXe1vvKzAW0NKWLx0nnTNrZxwzrNjZf?usp=drive_link, and put it under `starter_blends/` (the file is too big to directly push to the github repo)

Step 2) after you `git pull`, you should be able to run the following command.

```bash
python main.py --starter_blend starter_blends/livingroom_scene.blend --blender_base blender_base/geonodes.py --blender_script blender_scripts/scene_placement_examples/livingroom.py --config configs/placement_livingroom.yaml
```
(we're using the blender_base of geometry nodes, because it's identical for placements)

This edits the starter scene, which looks like:
![source](https://github.com/user-attachments/assets/9ca13f73-2058-4599-9592-32fcc106fc87)

Within the yaml, you'll see the target prompt:
"A modern livingroom with a sofa and a table, with a painting on the front and center of the wall and a plant between the sofa and the window wall. Another stack of books sits on the top of the coffee table."

Running this should generate 4 different options that you can peruse through (specified by `num_tries` in the yaml).

One of the edit trajectories  looked like this for me (edit iterations 1, 2, 3, 4 shown below):

![best_of](https://github.com/user-attachments/assets/1506db87-84de-45ee-965e-0e6c8654c2d6)

The rightmost one is the final output, and satisfies the painting insertion, plant placement, and adding another stack of books on the coffee table.

Note a few things though:

1) To answer your question, GPT (or any other current VLMs) seem to struggle the most with scene layout editing. We have ongoing work to address this, which we hope to release soon -- stay tuned!

2) I implemented a few helper functions inside the starter python script which VLMs are supposed to use to complete the placement task, though these are VERY simple helper functions (and may not apply to other scenes easily). You can imagine adding a larger library of helper functions. This is one of the objectives of the aforementioned ongoing work.

3) A lot of the assets are initially out of frame -- this is true for the plants, the books, the wall art, and a few other things. You can see them all if you open up the .blend file within Blender.
